// Common disposable / temporary / anonymous email providers.
const DISPOSABLE_EMAIL_DOMAINS = new Set([
    "10minutemail.com",
    "10minutemail.net",
    "20minutemail.com",
    "20minutemail.it",
    "33mail.com",
    "anonaddy.com",
    "anonaddy.me",
    "burnermail.io",
    "byom.de",
    "dispostable.com",
    "dropmail.me",
    "duck.com",
    "duckduckgo.com",
    "emailondeck.com",
    "fakeinbox.com",
    "fakemail.net",
    "fakermail.com",
    "getairmail.com",
    "getnada.com",
    "guerrillamail.biz",
    "guerrillamail.com",
    "guerrillamail.de",
    "guerrillamail.info",
    "guerrillamail.net",
    "guerrillamail.org",
    "guerrillamailblock.com",
    "harakirimail.com",
    "inboxbear.com",
    "inboxkitten.com",
    "inboxalias.com",
    "incognitomail.com",
    "jetable.org",
    "kasmail.com",
    "lroid.com",
    "mailcatch.com",
    "maildrop.cc",
    "mailforspam.com",
    "mailinator.com",
    "mailinator.net",
    "mailinator.org",
    "mailmoat.com",
    "mailnesia.com",
    "mailnull.com",
    "mailpoof.com",
    "mailsac.com",
    "mailtemp.info",
    "mintemail.com",
    "mohmal.com",
    "moakt.com",
    "mt2015.com",
    "mt2014.com",
    "my10minutemail.com",
    "mytemp.email",
    "mytrashmail.com",
    "nobulk.com",
    "noclickemail.com",
    "noidremember.com",
    "nope.email",
    "onetimeuse.org",
    "owlymail.com",
    "pokemail.net",
    "putthisinyourspamdatabase.com",
    "rcpt.at",
    "shitmail.me",
    "simplelogin.io",
    "simplelogin.com",
    "slmail.me",
    "spam4.me",
    "spambog.com",
    "spambog.de",
    "spambog.ru",
    "spambox.us",
    "spamfree24.com",
    "spamfree24.de",
    "spamfree24.eu",
    "spamfree24.info",
    "spamfree24.net",
    "spamfree24.org",
    "spamgourmet.com",
    "spamhole.com",
    "spammotel.com",
    "spamthis.co.uk",
    "tempail.com",
    "temp-mail.io",
    "temp-mail.org",
    "temp-mail.com",
    "tempinbox.com",
    "tempmail.dev",
    "tempmail.email",
    "tempmail.io",
    "tempmail.net",
    "tempmail.plus",
    "tempmail.us.com",
    "tempmailaddress.com",
    "tempmailo.com",
    "throwawaymail.com",
    "trash-mail.com",
    "trashmail.com",
    "trashmail.de",
    "trashmail.io",
    "trashmail.me",
    "trashmail.net",
    "trashmail.ws",
    "tutanota.com",
    "tuta.io",
    "wegwerfemail.de",
    "wegwerfmail.de",
    "wegwerfmail.net",
    "wegwerfmail.org",
    "yopmail.com",
    "yopmail.net",
    "yopmail.fr",
    "yopmail.gq",
    "yoggm.com",
    "zetmail.com",
]);

function getEmailDomain(email) {
    if (typeof email !== "string") return null;
    const at = email.lastIndexOf("@");
    if (at === -1 || at === email.length - 1) return null;
    return email.slice(at + 1).trim().toLowerCase();
}

function isDisposableEmail(email) {
    const domain = getEmailDomain(email);
    if (!domain) return false;
    if (DISPOSABLE_EMAIL_DOMAINS.has(domain)) return true;
    const parts = domain.split(".");
    for (let i = 1; i < parts.length - 1; i += 1) {
        const parent = parts.slice(i).join(".");
        if (DISPOSABLE_EMAIL_DOMAINS.has(parent)) return true;
    }
    return false;
}

module.exports = { isDisposableEmail, DISPOSABLE_EMAIL_DOMAINS };
